// Regenerates src/fonts/fonts.css and vendors the woff2 files it references.
//
// pica-ui used to @import six families from fonts.googleapis.com, which meant
// every app on the design system phoned Google on every page load. The fleet is
// self-hosted and has to render on a box with no egress, so the faces live here.
//
// Two sources, because the two halves arrived differently:
//   - the six original families come from @fontsource packages (devDependencies)
//   - Bodoni Moda / Spectral / Space Mono were already vendored by notes-srv-v2
//     for the prose look; its fonts.css is correct and subset-aware, so it is
//     appended verbatim rather than rebuilt.
//
// Only woff2 is vendored. The .woff fallback fontsource also ships is for
// browsers that predate every version of Svelte this package requires.
import { copyFileSync, existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const OUT = join(ROOT, 'src/fonts')
const NOTES_FONTS = '/home/apps/notes-srv-v2/src/fonts'

const FONTSOURCE = [
  'space-grotesk',
  'dm-sans',
  'ibm-plex-sans',
  'barlow-condensed',
  'lora',
  'jetbrains-mono',
]

// The weights components actually ask for: body 400, medium 500, semibold 600,
// bold 700. Vendoring every weight fontsource ships would triple the payload for
// faces nothing renders.
const WEIGHTS = new Set(['400', '500', '600', '700'])

function subsetFiles(pkgDir) {
  return readdirSync(pkgDir)
    .filter((f) => /^(latin|latin-ext)\.css$/.test(f))
    .sort()
}

function renderFontsource() {
  const chunks = []
  for (const pkg of FONTSOURCE) {
    const dir = join(ROOT, 'node_modules/@fontsource', pkg)
    if (!existsSync(dir)) throw new Error(`missing @fontsource/${pkg} — run bun install`)

    for (const cssFile of subsetFiles(dir)) {
      const css = readFileSync(join(dir, cssFile), 'utf8')
      for (const block of css.split('@font-face').slice(1)) {
        const weight = block.match(/font-weight:\s*(\d+)/)?.[1]
        if (!weight || !WEIGHTS.has(weight)) continue

        const woff2 = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)?.[1]
        if (!woff2) continue

        copyFileSync(join(dir, 'files', woff2), join(OUT, woff2))

        // Keep only the woff2 source; drop the woff fallback and the ./files/ prefix.
        const body = block
          .replace(/src:[^;]+;/, `src: url(./${woff2}) format('woff2');`)
          .trimEnd()
          .replace(/\}\s*$/, '}')
        chunks.push(`@font-face${body}`)
      }
    }
  }
  return chunks.join('\n\n')
}

function renderVendored() {
  // Already in src/fonts with correct relative urls — copied from notes-srv-v2.
  return readFileSync(join(NOTES_FONTS, 'fonts.css'), 'utf8').trim()
}

const header = `/* pica-ui — self-hosted faces.
   GENERATED by scripts/build-fonts.mjs — do not edit by hand.

   No third-party requests: the fleet must render on a box with no egress, and a
   self-hosted design system should not tell every visitor to call Google.
   Only the family the ACTIVE theme names is ever downloaded — an unused
   @font-face costs nothing until something renders in it. */

`

writeFileSync(
  join(OUT, 'fonts.css'),
  header + renderFontsource() + '\n\n' + renderVendored() + '\n',
)
console.log('fonts.css regenerated')
